"""auto-vote

Revision ID: bbaa0fda882d
Revises: 8bc3a6fcce43
Create Date: 2022-04-04 05:35:29.565935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbaa0fda882d'
down_revision = '8bc3a6fcce43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
